---
    extends: airbnb/base

    env:
        browser: true
        commonjs: true
        es6: true

    rules:
        brace-style:
            - error
            - stroustrup

        comma-dangle:
            - error
            - only-multiline

        curly:
            - error
            - multi-or-nest

        func-names: off

        indent:
            - error
            - tab
            - { "SwitchCase": 1 }

        max-len: warn
        new-cap: off
        no-confusing-arrow: off
        no-console: off
        no-extend-native: off
        no-global-assign: warn
        no-mixed-operators: off
        no-nested-ternary: off
        no-param-reassign: off
        no-prototype-builtins: warn
        no-restricted-syntax: off
        no-return-assign: off
        no-undef: warn
        no-underscore-dangle: off
        no-unsafe-negation: warn
        no-unused-expressions: warn
        no-use-before-define: off

        object-shorthand: off
        one-var: off

        prefer-const: off
        prefer-rest-params: off
        prefer-template: off

        space-infix-ops: warn

        quotes:
            - error
            - double





